### ISSUE TITLE
P0 - Repair and enhance monitoring config [EPIC]

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-monitor#11]
There are some issues with logging and monitoring that need to be addressed - these are visible across the stack. I was able to pinpoint some issues that make a huge difference.

- fix promtail bug per deployment (add persistent directory in docker-compose.yml)
- update version number for stack components in env per deployment
- revise promtail config per deployment (they need to be checked on and sometimes customized for the deployment)
- observe changes per deployment

**Comment by geleeroyale** [comment]
Task complete for arbitrage bots:

- Fixed promtail issues for lbank-arb-bot
- Add additional cadVisor monitoring to arbitrage bot servers
- Add custom alert for lbank-bot

**Comment by geleeroyale** [comment]
Giveth deployments that need update:

- [x] deVouch - Prod
- [x] deVouch - Staging
- [x] giveth-all - Prod
- [x] giveth-all Staging
- [x] giv-arb-bot
- [x] services

**Comment by geleeroyale** [comment]
- also updated all versions to latest stable for logs.giveth.io
- fixed breaking changes for loki-config.yaml:
LOKI_VERSION=3.3.2
CADDY_VERSION=2.8.4
GRAFANA_VERSION=11.4.0
PROMETHEUS_VERSION=v3.0.1
ALERTMANAGER_VERSION=v0.27.0
BLACKBOXEXPORTER_VERSION=v0.25.0
POSTGRES_EXPORTER_VERSION=v0.14.0
CADVISOR_VERSION=v0.49.2

**Comment by geleeroyale** [comment]
Moving this to Review and create similar issue to update monitoring stack for GM
